// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_meldrumn.Models;

namespace Mission06_meldrumn.Migrations
{
    [DbContext(typeof(MovieAppContext))]
    partial class MovieAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_meldrumn.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Action/Adventure",
                            Director = "Joss Whedon",
                            Edited = "No",
                            LentTo = "",
                            Notes = "A Certified Classic",
                            Rating = "PG-13",
                            Title = "The Avengers",
                            Year = (short)2012
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Action/Adventure",
                            Director = "Christopher Nolan",
                            Edited = "",
                            LentTo = "",
                            Notes = "Top Tier",
                            Rating = "PG-13",
                            Title = "Tenet",
                            Year = (short)2020
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Action/Adventure",
                            Director = "Peter Ramsey, Bob Persichetti, Rodney Rothman",
                            Edited = "No",
                            LentTo = "",
                            Notes = "Best Movie of All Time",
                            Rating = "PG",
                            Title = "Spider-Man: Into the Spider-Verse",
                            Year = (short)2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
